<a href="https://colab.research.google.com/github/MikaSiders/Nm/blob/main/%22%D0%BB%D0%B0%D0%B1%D0%B04_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# --- Вхідні дані (Варіант 30) ---
A = np.matrix([
    [4, 1, 4],
    [1, 1, 2],
    [2, 1, 2]
], dtype=float)

B = np.matrix([
    [-2],
    [-1],
    [0]
], dtype=float)

print("Матриця A:\n", A)
print("Вектор B:\n", B)
print("-" * 30)

# --- 1. Метод Крамера ---
def solve_cramer(a, b):
    print("\n--- Метод Крамера ---")
    det_a = np.linalg.det(a)
    print(f"Головний визначник (det A) = {det_a:.4f}")

    if np.isclose(det_a, 0):
        print("Визначник дорівнює нулю, метод Крамера не застосовується.")
        return None

    # Створення допоміжних матриць
    a_x = a.copy()
    a_x[:, 0] = b  # Заміна 1-го стовпця

    a_y = a.copy()
    a_y[:, 1] = b  # Заміна 2-го стовпця

    a_z = a.copy()
    a_z[:, 2] = b  # Заміна 3-го стовпця

    det_x = np.linalg.det(a_x)
    det_y = np.linalg.det(a_y)
    det_z = np.linalg.det(a_z)

    print(f"det X = {det_x:.4f}")
    print(f"det Y = {det_y:.4f}")
    print(f"det Z = {det_z:.4f}")

    x = det_x / det_a
    y = det_y / det_a
    z = det_z / det_a

    print(f"Результат: x = {x:.4f}, y = {y:.4f}, z = {z:.4f}")
    return x, y, z

# --- 2. Матричний метод (Обернена матриця) ---
def solve_matrix_method(a, b):
    print("\n--- Матричний метод ---")
    try:
        a_inv = np.linalg.inv(a)
        print("Обернена матриця A^(-1):\n", a_inv)

        X = a_inv.dot(b)
        print(f"Результат (X = A^(-1) * B):\n{X}")
        return X
    except np.linalg.LinAlgError:
        print("Матриця вироджена, оберненої матриці не існує.")
        return None

# --- 3. Метод Гауса ---
def solve_gauss(a_in, b_in):
    print("\n--- Метод Гауса ---")
    # Копіюємо, щоб не змінювати глобальні змінні
    a = np.copy(a_in)
    b = np.copy(b_in)
    n = len(b)
    x = np.zeros(n)

    # Прямий хід
    for k in range(n - 1):
        for i in range(k + 1, n):
            if a[k, k] == 0:
                continue # Спрощена обробка ділення на нуль
            factor = a[i, k] / a[k, k]
            for j in range(k, n):
                a[i, j] = a[i, j] - factor * a[k, j]
            b[i] = b[i] - factor * b[k]

    # Зворотний хід
    x[n - 1] = b[n - 1] / a[n - 1, n - 1]
    for i in range(n - 2, -1, -1):
        sum_ax = 0
        for j in range(i + 1, n):
            sum_ax += a[i, j] * x[j]
        x[i] = (b[i] - sum_ax) / a[i, i]

    print(f"Результат: {x}")
    return x

# --- Виклик функцій ---
solve_cramer(A, B)
solve_matrix_method(A, B)
solve_gauss(A, B)

# Перевірка вбудованим засобом
print("\n--- Перевірка (np.linalg.solve) ---")
print(np.linalg.solve(A, B))

Матриця A:
 [[4. 1. 4.]
 [1. 1. 2.]
 [2. 1. 2.]]
Вектор B:
 [[-2.]
 [-1.]
 [ 0.]]
------------------------------

--- Метод Крамера ---
Головний визначник (det A) = -2.0000
det X = -2.0000
det Y = -4.0000
det Z = 4.0000
Результат: x = 1.0000, y = 2.0000, z = -2.0000

--- Матричний метод ---
Обернена матриця A^(-1):
 [[-1.66533454e-16 -1.00000000e+00  1.00000000e+00]
 [-1.00000000e+00 -2.96059473e-16  2.00000000e+00]
 [ 5.00000000e-01  1.00000000e+00 -1.50000000e+00]]
Результат (X = A^(-1) * B):
[[ 1.]
 [ 2.]
 [-2.]]

--- Метод Гауса ---
Результат: [ 1.  2. -2.]

--- Перевірка (np.linalg.solve) ---
[[ 1.]
 [ 2.]
 [-2.]]


/tmp/ipython-input-131746501.py:89: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  x[n - 1] = b[n - 1] / a[n - 1, n - 1]
/tmp/ipython-input-131746501.py:94: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  x[i] = (b[i] - sum_ax) / a[i, i]
